version: "3.9"

services:
  php:
    build: ./backend
    container_name: critique-php
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: critique-nginx
    ports:
      - "8080:80" # ホスト8080 -> nginx 80
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: critique-postgres
    environment:
      POSTGRES_DB: critique
      POSTGRES_USER: critique
      POSTGRES_PASSWORD: critique
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

